### ISSUE TITLE
Issue with subtraction with decimals

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#6]
**Describe the bug**
Some results found using subtraction option:
4 - 1.4 = -3.4
3 - 1.7 = -2.7
-4 - 1.4 =  -54
3 - (-1.7) = 47

Also issue with addition with negative numbers.
3 + (-1.6) = 14
3 + (-1.5) = 15

**Comment by VirxEC** [comment]
This issue has been partially fixed:
-4 - 1.4 = -5.4 instead of -54
3 - (-1.7) = 4.7 instead of 47
3 + (-1.6) = 1.4 instead of 14
3 + (-1.5) = 1.5 instead of 15

**Comment by VirxEC** [comment]
Still need to fix:
4 - 1.4 = -3.4
3 - 1.7 = -2.7

**Comment by yunfeizhengcoder** [comment]
Hey I found some other errors
10 + (-1.1) = 19.NaN
30 + (-0.1) = 29.NaN

**Comment by VirxEC** [comment]
Fixed this:
4 - 1.4 = 2.6 (instead of -3.4)
However, now:
4 - 4.4 = 1.6

**Comment by VirxEC** [comment]
Ok I think I broke the subtraction & addition functions, but I think that it's more that before it was in a state that worked some of the time, and now that I'm trying to get it to work all of the time I'm changing things that were less "correct" than "lucky bugs" and then they because actual bugs instead... RIP

**Comment by VirxEC** [comment]
This issue has been fixed
